#!/usr/bin/env node
/**
 * Generate `plugins/all.grit` from the individual plugin files.
 *
 * Biome resolves `plugins` entries as explicit file paths — no globs, no
 * directories, no bare package specifiers (all three were tried against 2.5).
 * So without an aggregate, every consumer has to list every plugin, and adding
 * one upstream means editing every `biome.json` downstream.
 *
 * GritQL's named patterns make the aggregate cheap: each plugin's body becomes
 * `pattern <slug>() { … }` and the file ends with an `or` over all of them.
 * The individual files stay the source of truth, so nothing is written twice —
 * `pnpm test` fails if this output is stale.
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const pluginsDir = join(root, "plugins");
const OUT = join(pluginsDir, "all.grit");

const files = readdirSync(pluginsDir)
  .filter((f) => f.endsWith(".grit") && f !== "all.grit")
  .sort();

const slug = (f) => f.replace(/\.grit$/, "").replace(/-/g, "_");

const body = files
  .map((f) => {
    const src = readFileSync(join(pluginsDir, f), "utf8").trimEnd();
    const indented = src
      .split("\n")
      .map((line) => (line.length ? `  ${line}` : line))
      .join("\n");
    return `pattern ${slug(f)}() {\n${indented}\n}`;
  })
  .join("\n\n");

const header = `// GENERATED by scripts/build-all.mjs — do not edit.
//
// Every plugin in this package, composed into one file so a consumer needs a
// single \`plugins\` entry:
//
//   "./node_modules/@common-pattern/biome-plugins/plugins/all.grit"
//
// Reference the individual files instead if you want only some of the rules.
// Each rule's reasoning lives in its own file; the comments below are carried
// over verbatim.
`;

const footer = `or { ${files.map((f) => `${slug(f)}()`).join(", ")} }\n`;

const output = `${header}\n${body}\n\n${footer}`;
writeFileSync(OUT, output);
console.log(`wrote plugins/all.grit from ${files.length} plugin(s): ${files.join(", ")}`);
